<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CoreVer Condition="'$(CoreVer)' == ''">0.2.11</CoreVer>
    <TransformVer Condition="'$(TransformVer)' == ''">0.2.9</TransformVer>
    <SourceGeneratorsVer Condition="'$(SourceGeneratorsVer)' == ''">0.2.12</SourceGeneratorsVer>
    <BuildVer Condition="'$(BuildVer)' == ''">0.2.1</BuildVer>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Silk.NET.Assimp" Version="2.23.0" />
    <PackageVersion Include="Solas.Core" Version="$(CoreVer)" />
    <PackageVersion Include="Solas.Transform" Version="$(TransformVer)" />
    <PackageVersion Include="Solas.SourceGenerators" Version="$(SourceGeneratorsVer)" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.3.0" />
    <PackageVersion Include="Silk.NET.Core" Version="2.23.0" />
    <PackageVersion Include="Silk.NET.Input" Version="2.23.0" />
    <PackageVersion Include="Silk.NET.Vulkan" Version="2.23.0" />
    <PackageVersion Include="Silk.NET.Vulkan.Extensions.EXT" Version="2.23.0" />
    <PackageVersion Include="Silk.NET.Vulkan.Extensions.KHR" Version="2.23.0" />
    <PackageVersion Include="Silk.NET.Windowing" Version="2.23.0" />
    <PackageVersion Include="StbImageSharp" Version="2.30.15" />
    <PackageVersion Include="SlangShaderSharp" Version="2026.13.1" />
  </ItemGroup>
</Project>