<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Solas.Render</RootNamespace>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <PackageId>Solas.Render</PackageId>
        <Version>0.3.0</Version>
        <Authors>NevskyV</Authors>
        <Description>High performance open-source .net game engine created specifically for indie devs</Description>
        <RepositoryUrl>https://github.com/NevskyV/Solas</RepositoryUrl>
        <PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\README.md" Pack="true" PackagePath="\"/>
        <PackageReference Include="Silk.NET.Assimp"/>
        <PackageReference Include="SlangShaderSharp"/>
        <PackageReference Include="Solas.Transform"/>

        <PackageReference Include="Silk.NET.Core"/>
        <PackageReference Include="Silk.NET.Input"/>
        <PackageReference Include="Silk.NET.Vulkan"/>
        <PackageReference Include="Silk.NET.Vulkan.Extensions.EXT"/>
        <PackageReference Include="Silk.NET.Vulkan.Extensions.KHR"/>
        <PackageReference Include="Silk.NET.Windowing"/>
        <PackageReference Include="StbImageSharp"/>
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="StandardShaders\**\*.*" Exclude="StandardShaders\Embedded\*.*">
            <Pack>true</Pack>
            <PackagePath>contentFiles/any/any/StandardShaders\%(RecursiveDir)%(Filename)%(Extension)</PackagePath>
            <PackageCopyToOutput>true</PackageCopyToOutput>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AdditionalFiles>
        <EmbeddedResource Include="StandardShaders\Embedded\*.spv"/>
    </ItemGroup>

</Project>
